=== germancordellat/2DAM/data-acces/UD3/ad.03.ejercicios.xmlparsing/colegio.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT colegio (grupo+)>
<!ELEMENT grupo (nombre,alumno+)>
<!ATTLIST grupo codigo CDATA "">
<!ATTLIST grupo maxalumnos CDATA "">
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT alumno (expediente, nombrealu, fechaingreso)>
<!ELEMENT expediente (#PCDATA)>
<!ELEMENT nombrealu (#PCDATA)>
<!ELEMENT fechaingreso (#PCDATA)>

=== germancordellat/2DAM/data-acces/UD3/ad.03.ejercicios.xmlparsing/grupos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE colegio SYSTEM "colegio.dtd">
<colegio>
	<grupo codigo ="1DAM" maxalumnos="24">
		<nombre>1ยบ DAM</nombre>
		<alumno>
			<expediente>6601</expediente>
			<nombrealu>David Gonzalez</nombrealu>
			<fechaingreso>01/09/2012</fechaingreso>
		</alumno>
		<alumno>
			<expediente>6602</expediente>
			<nombrealu>Pedro Moreno</nombrealu>
			<fechaingreso>01/09/2012</fechaingreso>
		</alumno>
		<alumno>
			<expediente>6603</expediente>
			<nombrealu>Julian Gomez</nombrealu>
			<fechaingreso>01/09/2012</fechaingreso>
		</alumno>
	</grupo>

	<grupo codigo ="2DAM" maxalumnos="24">
		<nombre>2ยบ DAM</nombre>
		<alumno>
			<expediente>6605</expediente>
			<nombrealu>Fernando Flores</nombrealu>
			<fechaingreso>01/03/2012</fechaingreso>
		</alumno>
		<alumno>
			<expediente>6606</expediente>
			<nombrealu>David Mancebo</nombrealu>
			<fechaingreso>01/05/2012</fechaingreso>
		</alumno>
		<alumno>
			<expediente>6607</expediente>
			<nombrealu>Laura Solsona</nombrealu>
			<fechaingreso>01/06/2012</fechaingreso>
		</alumno>
	</grupo>
</colegio>
